default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV["DATABASE_HOST"] %>
  database: <%= ENV["DATABASE"] %>
  username: <%= ENV["DBUSER"] %>
  password: <%= ENV["DBPASSWORD"] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: facebook_rails_tdd_development

test:
  <<: *default
  database: facebook_rails_tdd_test

production:
  <<: *default
  database: facebook_rails_tdd_production
  username: facebook_rails_tdd
  password: <%= ENV["FACEBOOK_RAILS_TDD_DATABASE_PASSWORD"] %>
